"""g4kit-convert-openhands: convert OpenHands SWE trajectories into the competition harness's tool format, for
distillation fine-tuning.

Source data: nebius/SWE-rebench-openhands-trajectories (CC-BY-4.0; generated by Qwen3-Coder-480B-A35B-Instruct,
Apache 2.0, with OpenHands 0.54). Keep the attribution when you redistribute converted data (see NOTICE).

Tool mapping (results use the harness's own JSON: ``{"status": "ok", ...}`` or ``{"status": "error",
"error_type", "error_message", "details"?}``):

  execute_bash                    -> run_command {command}; result {status, stdout, stderr, exit_code} or CommandError
  str_replace_editor view (file)  -> read_file {filepath, start_line?, end_line?}; ``cat -n`` prefixes stripped;
                                     views over the read_file caps become consecutive range reads
  str_replace_editor view (dir)   -> run_command ``find <dir> -maxdepth 2 -not -path '*/.*'``
  str_replace_editor create       -> write_file {filepath, content} for repository files; scratch scripts at the
                                     repository root become ``run_command`` heredocs under /tmp (the harness's
                                     write_file rejects paths outside /workspace), and later commands follow them
  str_replace_editor str_replace  -> edit_file {filepath, old_string, new_string}; result carries a unified diff
  think                           -> folded into the next assistant turn's reasoning
  task_tracker                    -> dropped
  finish                          -> submit_patch {} (result {status, patch_size, files_changed}), then a short text reply

Paths ``/workspace/<repo>__<version>`` become ``/workspace`` in commands and repository-relative paths in file
tools. A trajectory is kept only if every step is consistent with what the harness would have shown: no
interactive input, undo or insert; file views within read_file's caps (150 lines, 10,000 characters per call,
at most 3 chunks); command output within run_command's 5,000-character cap (the harness keeps the FIRST 5,000
characters, so a longer output becomes ``cmd 2>&1 | tail -n N`` when the command allows it).

Output JSONL, one trajectory per line: {instance_id, repo, issue, n_turns, messages}. Messages are OpenAI style:
assistant {content, reasoning, tool_calls with dict arguments}, tool {tool_call_id, name, content}, where tool
content is the harness's JSON string; g4kit-render-distill applies the scorer's encoding.
"""
from __future__ import annotations

import argparse
import collections
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable, Iterator

MAX_LINES, MAX_FILE_CHARS, MAX_STDOUT = 150, 10000, 5000   # swegemma HarnessLimits defaults
MAX_VIEW_CHUNKS = 3
EXIT_RE = re.compile(r"\n?\[(?:The command completed|Command finished) with exit code (-?\d+)\.?\]")
TRAILER_RE = re.compile(r"\n?\[(Current working directory|Python interpreter): [^\]]*\]")
VIEW_HDR = re.compile(r"^Here's the result of running `cat -n` on (\S+?):\n")
EDIT_OK = re.compile(r"^The file (\S+) has been edited\. Here's the result of running `cat -n` on a snippet of \S+:\n")
CREATE_OK = re.compile(r"^File created successfully at: (\S+)")
NUM_LINE = re.compile(r"^ *(\d+)\t(.*)$")


class Skip(Exception):
    """The trajectory cannot be expressed faithfully in the harness's tools; the message is the reason."""


def ok(**kw: Any) -> str:
    d: dict[str, Any] = {"status": "ok"}
    d.update(kw)
    return json.dumps(d, ensure_ascii=False)


def err(etype: str, msg: str, details: dict | None = None) -> str:
    d: dict[str, Any] = {"status": "error", "error_type": etype, "error_message": msg}
    if details is not None:
        d["details"] = details
    return json.dumps(d, ensure_ascii=False)


def numbered(text: str) -> tuple[int, list[str]]:
    """``cat -n`` body -> (first line number, [lines])."""
    first, lines = None, []
    for ln in text.split("\n"):
        m = NUM_LINE.match(ln)
        if not m:
            if ln.strip() == "":
                continue
            raise Skip("view_format")
        if first is None:
            first = int(m.group(1))
        lines.append(m.group(2))
    return first or 1, lines


def text_of(content: Any) -> str:
    if isinstance(content, list):
        return "".join(p.get("text", "") for p in content if isinstance(p, dict))
    return content or ""


class Conv:
    def __init__(self, row: dict, *, max_lines: int = MAX_LINES, max_file_chars: int = MAX_FILE_CHARS,
                 max_stdout: int = MAX_STDOUT):
        self.row = row
        self.max_lines, self.max_file_chars, self.max_stdout = max_lines, max_file_chars, max_stdout
        user = next((text_of(m.get("content")) for m in row["trajectory"] if m["role"] == "user"), "")
        m = re.search(r"<uploaded_files>\s*(/workspace/[^\s<]+)\s*</uploaded_files>", user)
        if not m:
            raise Skip("no_workspace")
        self.root = m.group(1).rstrip("/")
        m = re.search(r"<issue_description>\n?(.*?)\n?</issue_description>", user, re.S)
        if not m:
            raise Skip("no_issue")
        self.issue = m.group(1).strip()
        self.scratch: dict[str, str] = {}      # repo-root scratch file name -> /tmp path
        self.files_changed: set[str] = set()
        self.gold_files = set(re.findall(r"^diff --git a/(\S+)", row.get("model_patch") or "", re.M))

    def rel(self, path: str) -> str:
        path = path.rstrip("/")
        if path in (self.root, "/workspace"):
            return "."
        if not path.startswith(self.root + "/"):
            raise Skip("path_outside_repo")
        return path[len(self.root) + 1:]

    def fix_text(self, s: str) -> str:
        s = s.replace(self.root + "/", "/workspace/").replace(self.root, "/workspace")
        for name, tmp in self.scratch.items():
            s = re.sub(r"(?<![\w/.])(?:/workspace/)?" + re.escape(name) + r"(?![\w.])", tmp, s)
        return s

    def bash(self, a: dict, obs: str):
        if str(a.get("is_input", "false")).lower() == "true":
            raise Skip("is_input")
        cmd = self.fix_text(a["command"])
        m = EXIT_RE.search(obs)
        code = int(m.group(1)) if m else None
        out = TRAILER_RE.sub("", EXIT_RE.sub("", obs)).rstrip("\n")
        if code is None:
            if "timed out" in obs.lower() or "no output" in obs.lower():
                raise Skip("bash_timeout")
            code = 0
        out = self.fix_text(out)
        if len(out) > self.max_stdout:
            # the teacher acted on the whole output (usually its end); the harness keeps the first 5,000 chars,
            # so the call becomes 'cmd 2>&1 | tail -n N' showing the last lines that fit (tail exits 0)
            if "<<" in cmd or "|" in cmd.split("\n")[-1][-40:]:
                raise Skip("stdout_cap")
            tail = out[-(self.max_stdout - 1000):]
            tail = tail[tail.find("\n") + 1:] if "\n" in tail else tail
            n = tail.count("\n") + 1
            return "run_command", {"command": f"{cmd} 2>&1 | tail -n {n}"}, ok(stdout=tail, stderr="", exit_code=0)
        if code == 0:
            return "run_command", {"command": cmd}, ok(stdout=out, stderr="", exit_code=0)
        return "run_command", {"command": cmd}, err("CommandError", out, {"stdout": out, "stderr": "", "exit_code": code})

    def view(self, a: dict, obs: str, path: str):
        if obs.startswith("Here's the files and directories"):
            target = self.rel(path)
            body = obs.split("\n", 1)[1] if "\n" in obs else ""
            seen: set[str] = set()
            rows = []
            for ln in self.fix_text(body).rstrip("\n").split("\n"):
                if ln not in seen:
                    seen.add(ln)
                    rows.append(ln)
            listing = "\n".join(rows)
            if len(listing) > self.max_stdout:
                raise Skip("stdout_cap")
            return "run_command", {"command": f"find {target} -maxdepth 2 -not -path '*/.*'"}, \
                ok(stdout=listing, stderr="", exit_code=0)
        m = VIEW_HDR.match(obs)
        if not m:
            if obs.startswith("ERROR"):
                return "read_file", {"filepath": self.rel(path)}, err("FileReadError", self.fix_text(obs))
            raise Skip("view_format")
        first, lines = numbered(obs[m.end():])
        content = "\n".join(lines)
        rel = self.rel(path)
        end = first + len(lines) - 1
        if len(lines) <= self.max_lines and len(content) <= self.max_file_chars:
            args: dict[str, Any] = {"filepath": rel}
            vr = a.get("view_range")
            if vr:
                args["start_line"] = int(vr[0])
                if int(vr[1]) != -1:
                    args["end_line"] = int(vr[1])
            return "read_file", args, ok(filepath=rel, content=content, start_line=first, end_line=end,
                                         total_lines=end, is_truncated=False)
        chunks, i = [], 0
        while i < len(lines):
            j = min(len(lines), i + self.max_lines)
            while j > i + 1 and len("\n".join(lines[i:j])) > self.max_file_chars:
                j -= 10 if j - i > 20 else 1
            chunks.append((i, j))
            i = j
        if len(chunks) > MAX_VIEW_CHUNKS:
            raise Skip("view_cap")
        return [("read_file", {"filepath": rel, "start_line": first + i, "end_line": first + j - 1},
                 ok(filepath=rel, content="\n".join(lines[i:j]), start_line=first + i, end_line=first + j - 1,
                    total_lines=end, is_truncated=False)) for i, j in chunks]

    def create(self, a: dict, obs: str, path: str):
        rel = self.rel(path)
        text = self.fix_text(a.get("file_text", ""))
        if not CREATE_OK.match(obs):
            raise Skip("create_failed")
        if "/" not in rel and rel.endswith(".py") and rel not in self.gold_files:
            tmp = "/tmp/" + rel
            self.scratch[rel] = tmp
            delim = "EOF" if "\nEOF\n" not in text else "PYEOF"
            return "run_command", {"command": f"cat > {tmp} <<'{delim}'\n{text}\n{delim}"}, \
                ok(stdout="", stderr="", exit_code=0)
        self.files_changed.add(rel)
        return "write_file", {"filepath": rel, "content": text}, ok(filepath=rel, size=len(text))

    def str_replace(self, a: dict, obs: str, path: str):
        rel = self.rel(path)
        old, new = a.get("old_str", ""), a.get("new_str", "")
        m = EDIT_OK.match(obs)
        if not m:
            msg = self.fix_text(obs.split("\n")[0])
            return "edit_file", {"filepath": rel, "old_string": old, "new_string": new}, err("FileEditError", msg)
        self.files_changed.add(rel)
        snippet = obs[m.end():].split("\nReview the changes")[0]
        try:
            first, lines = numbered(snippet)
        except Skip:
            lines, first = [], 1
        new_lines = new.split("\n")
        start = next((i for i in range(len(lines)) if lines[i:i + len(new_lines)] == new_lines), None)
        if start is None:
            before, after, lineno = [], [], 1
        else:
            before = lines[max(0, start - 3):start]
            after = lines[start + len(new_lines):start + len(new_lines) + 3]
            lineno = first + start - len(before)
        a_lines = [ln + "\n" for ln in before + old.split("\n") + after]
        b_lines = [ln + "\n" for ln in before + new_lines + after]
        diff = list(difflib.unified_diff(a_lines, b_lines, fromfile=f"a/{rel}", tofile=f"b/{rel}"))
        if lineno > 1 and len(diff) > 2:
            def shift(h: str) -> str:
                return re.sub(r"@@ -(\d+)(,\d+)? \+(\d+)(,\d+)? @@",
                              lambda q: f"@@ -{int(q.group(1)) + lineno - 1}{q.group(2) or ''} "
                                        f"+{int(q.group(3)) + lineno - 1}{q.group(4) or ''} @@", h)
            diff = [shift(h) if h.startswith("@@") else h for h in diff]
        return "edit_file", {"filepath": rel, "old_string": old, "new_string": new}, \
            ok(filepath=rel, occurrences=1, strategy="exact", diff="".join(diff), is_truncated=False)

    def editor(self, a: dict, obs: str):
        cmd, path = a.get("command"), a.get("path", "")
        if cmd in ("undo_edit", "insert"):
            raise Skip(cmd)
        if cmd == "view":
            return self.view(a, obs, path)
        if cmd == "create":
            return self.create(a, obs, path)
        if cmd == "str_replace":
            return self.str_replace(a, obs, path)
        raise Skip("editor_" + str(cmd))

    def convert(self) -> dict:
        row = self.row
        msgs: list[dict] = []
        pending_reason: list[str] = []
        n_turns, finished = 0, False
        traj = row["trajectory"]
        by_id = {m.get("tool_call_id"): m for m in traj if m["role"] == "tool"}
        for m in traj:
            if m["role"] != "assistant":
                continue
            text = text_of(m.get("content")).strip()
            calls_out, results, thoughts = [], [], []
            for tc in m.get("tool_calls") or []:
                f = tc["function"]
                try:
                    a = f["arguments"] if isinstance(f["arguments"], dict) else json.loads(f["arguments"])
                except (ValueError, TypeError):
                    raise Skip("badjson") from None
                obs_m = by_id.get(tc.get("id"))
                obs = text_of((obs_m or {}).get("content"))
                name = f["name"]
                if name == "think":
                    thoughts.append((a.get("thought") or "").strip())
                    continue
                if name == "task_tracker":
                    continue
                if name == "finish":
                    finished = True
                    patch = row.get("model_patch") or ""
                    calls_out.append(("submit_patch", {}))
                    results.append(ok(patch_size=len(patch), files_changed=patch.count("diff --git")))
                    continue
                if obs_m is None:
                    raise Skip("missing_obs")
                if name == "execute_bash":
                    out = self.bash(a, obs)
                elif name == "str_replace_editor":
                    out = self.editor(a, obs)
                else:
                    raise Skip("tool_" + name)
                for tn, ta, res in (out if isinstance(out, list) else [out]):
                    calls_out.append((tn, ta))
                    results.append(res)
            pending_reason += ([text] if text else []) + thoughts
            if not calls_out:
                continue            # a text-only or dropped-tool turn: its text rides on the next call
            reason = self.fix_text("\n\n".join(r for r in pending_reason if r))
            pending_reason = []
            ids = [f"call_{len(msgs)}_{i}" for i in range(len(calls_out))]
            msgs.append({"role": "assistant", "content": None, "reasoning": reason or None,
                         "tool_calls": [{"id": i, "type": "function", "function": {"name": n, "arguments": a}}
                                        for i, (n, a) in zip(ids, calls_out, strict=True)]})
            for i, (n, _), res in zip(ids, calls_out, results, strict=True):
                msgs.append({"role": "tool", "tool_call_id": i, "name": n, "content": res})
            n_turns += 1
            if finished:
                break
        if not finished:
            raise Skip("no_finish")
        msgs.append({"role": "assistant", "content": "Submitted the fix.", "reasoning": None})
        return {"instance_id": row["instance_id"], "repo": row["repo"], "issue": self.issue, "n_turns": n_turns,
                "messages": msgs}


COLUMNS = ["instance_id", "repo", "resolved", "trajectory", "model_patch"]


def iter_rows(src: str, row_groups: str | None = None) -> Iterator[dict]:
    """Rows from parquet file(s) (a file or a directory) or a JSONL file."""
    path = Path(src)
    if path.suffix == ".jsonl":
        with open(path, encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    yield json.loads(line)
        return
    import pyarrow.parquet as pq

    files = sorted(path.glob("**/*.parquet")) if path.is_dir() else [path]
    lo, hi = (map(int, row_groups.split("-")) if row_groups else (0, 10 ** 9))
    for file in files:
        pf = pq.ParquetFile(file)
        for g in range(lo, min(hi, pf.num_row_groups - 1) + 1):
            yield from pf.read_row_group(g, columns=COLUMNS).to_pylist()


def convert_rows(rows: Iterable[dict], *, max_turns: int = 40, per_instance: int = 2, resolved_only: bool = True,
                 **limits: int) -> tuple[list[dict], collections.Counter]:
    why: collections.Counter = collections.Counter()
    per_inst: collections.Counter = collections.Counter()
    kept = []
    for row in rows:
        if resolved_only and not row.get("resolved"):
            why["unresolved"] += 1
            continue
        if per_inst[row["instance_id"]] >= per_instance:
            why["per_instance"] += 1
            continue
        try:
            out = Conv(row, **limits).convert()
        except Skip as exc:
            why[str(exc)] += 1
            continue
        if out["n_turns"] > max_turns:
            why["too_long"] += 1
            continue
        per_inst[row["instance_id"]] += 1
        kept.append(out)
    return kept, why


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="g4kit-convert-openhands", description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("src", help="trajectories parquet file or directory (Hugging Face download), or a .jsonl file")
    ap.add_argument("out", help="output JSONL")
    ap.add_argument("--max-turns", type=int, default=40)
    ap.add_argument("--per-instance", type=int, default=2, help="trajectories kept per task instance")
    ap.add_argument("--row-groups", help="parquet row-group range, e.g. 0-16")
    ap.add_argument("--include-unresolved", action="store_true")
    ap.add_argument("--max-lines", type=int, default=MAX_LINES, help="read_file line cap")
    ap.add_argument("--max-file-chars", type=int, default=MAX_FILE_CHARS, help="read_file character cap")
    ap.add_argument("--max-stdout", type=int, default=MAX_STDOUT, help="run_command output cap")
    a = ap.parse_args(argv)
    kept, why = convert_rows(iter_rows(a.src, a.row_groups), max_turns=a.max_turns, per_instance=a.per_instance,
                             resolved_only=not a.include_unresolved, max_lines=a.max_lines,
                             max_file_chars=a.max_file_chars, max_stdout=a.max_stdout)
    with open(a.out, "w", encoding="utf-8") as f:
        for conv in kept:
            f.write(json.dumps(conv, ensure_ascii=False) + "\n")
    print(f"kept {len(kept)} trajectories from {len({c['instance_id'] for c in kept})} instances; "
          f"skipped {dict(why.most_common())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
